-- Seed questions table with basketball rules questions
INSERT INTO questions (text, correct_answer, subject, category) VALUES
('Can a player dribble with two hands simultaneously?', false, 'Dribbling', 'Ball Handling'),
('Is it legal to block a shot after it hits the backboard?', true, 'Defense', 'Defensive Play'),
('Can the ball handler lift their pivot foot before releasing the ball on a dribble?', true, 'Footwork', 'Movement'),
('Is it a violation if a player''s foot touches the baseline while inbounding the ball?', true, 'Boundaries', 'Court Rules'),
('Can a player call a timeout while falling out of bounds with possession of the ball?', true, 'Timeouts', 'Game Management'),
('Is it legal to jump from out of bounds and save a ball before landing inbounds?', false, 'Boundaries', 'Court Rules'),
('Can a defensive player take a charge in the restricted area under the basket?', false, 'Defense', 'Defensive Play'),
('Is it legal for a player to touch the ball while any part of their body is touching the sideline?', false, 'Boundaries', 'Court Rules'),
('Can a player receive a technical foul for hanging on the rim after a dunk?', true, 'Fouls', 'Penalties'),
('Is it legal to pass the ball to yourself without it touching another player or the backboard?', false, 'Passing', 'Ball Handling'),
('Can a player be called for traveling if they take more than two steps after gathering the ball?', true, 'Traveling', 'Movement'),
('Is it legal to touch the ball after it hits the rim when the ball is above the cylinder?', false, 'Goaltending', 'Defensive Play'),
('Can a player be called for a 3-second violation while their team does not have possession of the ball?', false, 'Violations', 'Rule Violations'),
('Is it legal to call a timeout when your team does not have possession of the ball?', false, 'Timeouts', 'Game Management'),
('Can a player be called for a backcourt violation if they were the last to touch the ball in the frontcourt?', true, 'Backcourt', 'Court Rules'),
('Is it legal to block a shot after it starts its downward flight?', false, 'Goaltending', 'Defensive Play'),
('Can a player step on the free throw line during a free throw attempt?', false, 'Free Throws', 'Shooting'),
('Is it legal for non-shooters to enter the lane before the ball hits the rim on a free throw?', false, 'Free Throws', 'Shooting'),
('Can a player be called for a 5-second violation while being closely guarded outside the 3-point line?', true, 'Violations', 'Rule Violations'),
('Is it legal to call a timeout while the ball is loose (not in possession of either team)?', false, 'Timeouts', 'Game Management'),
('Can a player be called for a kicked ball violation if the ball is accidentally kicked?', true, 'Violations', 'Rule Violations'),
('Is it legal to touch the ball after a made basket before it is inbounded?', false, 'Inbounding', 'Game Management'),
('Can a player be called for a lane violation if they enter the lane before the shooter releases the ball?', true, 'Free Throws', 'Shooting'),
('Is it legal for a player to touch their teammates'' free throw attempt before it hits the rim?', false, 'Free Throws', 'Shooting'),
('Can a player be called for a 3-second violation while in the act of shooting?', false, 'Violations', 'Rule Violations'),
('Is it legal to call a timeout while in the air with possession of the ball?', true, 'Timeouts', 'Game Management'),
('Can a player be called for traveling if they land on both feet and then lift their pivot foot?', false, 'Traveling', 'Movement'),
('Is it legal to dribble, stop, and then begin dribbling again?', false, 'Dribbling', 'Ball Handling'),
('Can a player be called for a technical foul for excessive celebration?', true, 'Fouls', 'Penalties'),
('Is it legal to touch the ball while any part of your body is touching the baseline?', false, 'Boundaries', 'Court Rules'),
('Can a player be called for a flagrant foul if there is no contact made?', false, 'Fouls', 'Penalties'),
('Is it legal to call a timeout while falling out of bounds without possession of the ball?', false, 'Timeouts', 'Game Management'),
('Can a player be called for a 10-second violation if they do not advance the ball past half court in time?', true, 'Violations', 'Rule Violations'),
('Is it legal to jump from the frontcourt and land in the backcourt with the ball?', false, 'Backcourt', 'Court Rules'),
('Can a player be called for a double dribble if they dribble with one hand, then the other?', false, 'Dribbling', 'Ball Handling'),
('Is it legal to touch the ball with your foot intentionally?', false, 'Violations', 'Rule Violations'),
('Can a player be called for a technical foul for arguing with an official?', true, 'Fouls', 'Penalties'),
('Is it legal to call a timeout when your team has none remaining?', false, 'Timeouts', 'Game Management'),
('Can a player be called for a 5-second violation while inbounding the ball?', true, 'Inbounding', 'Game Management'),
('Is it legal to block a shot before it reaches its apex?', true, 'Defense', 'Defensive Play'),
('Can a player be called for a traveling violation if they slide across the floor with the ball?', true, 'Traveling', 'Movement'),
('Is it legal to touch the ball after a throw-in before it touches another player?', false, 'Inbounding', 'Game Management'),
('Can a player be called for a 3-second violation if only one foot is in the lane?', true, 'Violations', 'Rule Violations'),
('Is it legal to call a timeout while the ball is in the air during a jump ball?', false, 'Timeouts', 'Game Management'),
('Can a player be called for a backcourt violation during a throw-in?', false, 'Backcourt', 'Court Rules'),
('Is it legal to touch the ball with your leg intentionally?', false, 'Violations', 'Rule Violations'),
('Can a player be called for a technical foul for unsportsmanlike conduct?', true, 'Fouls', 'Penalties'),
('Is it legal to dunk during pre-game warmups?', false, 'Equipment', 'Game Rules'),
('Can a player be called for a shot clock violation if they shoot before the buzzer but the ball doesn''t hit the rim?', true, 'Shot Clock', 'Game Management'),
('Is it legal to wear jewelry during a game?', false, 'Equipment', 'Game Rules');

-- Seed study_resources table
INSERT INTO study_resources (subject, title, description, url, type) VALUES
('Dribbling', 'Basketball Dribbling Rules Explained', 'A comprehensive guide to all dribbling rules and violations', 'https://www.basketball-reference.com/about/rules.html', 'article'),
('Defense', 'Defensive Rules in Basketball', 'Learn about legal defensive positions and techniques', 'https://www.usab.com/youth/news/2012/08/five-basic-basketball-defensive-concepts.aspx', 'article'),
('Footwork', 'Mastering Basketball Footwork', 'Detailed explanation of pivot foot rules and traveling violations', 'https://www.breakthroughbasketball.com/fundamentals/footwork.html', 'video'),
('Boundaries', 'Court Boundaries and Violations', 'Understanding the boundary lines and related rules', 'https://www.basketball-reference.com/about/rules.html', 'article'),
('Timeouts', 'Timeout Rules in Basketball', 'When and how timeouts can be called during a game', 'https://official.nba.com/rule-no-5-scoring-and-timing/', 'article'),
('Fouls', 'Basketball Fouls Explained', 'Different types of fouls and their consequences', 'https://www.basketball-reference.com/about/rules.html#fouls', 'course'),
('Traveling', 'Traveling Violations Explained', 'Detailed breakdown of traveling rules with examples', 'https://official.nba.com/rule-no-10-violations-and-penalties/', 'video'),
('Goaltending', 'Goaltending and Basket Interference', 'Understanding when a block is legal vs. goaltending', 'https://official.nba.com/rule-no-11-basket-interference-goaltending/', 'article'),
('Violations', 'Common Basketball Violations', 'Comprehensive guide to all violations in basketball', 'https://www.basketball-reference.com/about/rules.html#violations', 'course'),
('Backcourt', 'Backcourt Violations Explained', 'When and how backcourt violations occur', 'https://official.nba.com/rule-no-10-violations-and-penalties/', 'article'),
('Free Throws', 'Free Throw Rules and Violations', 'Complete guide to free throw procedures and violations', 'https://official.nba.com/rule-no-9-free-throws-and-penalties/', 'video'),
('Inbounding', 'Inbounding Rules in Basketball', 'Proper procedures for inbounding the ball', 'https://www.basketball-reference.com/about/rules.html', 'article'),
('Shot Clock', 'Understanding the Shot Clock', 'Rules and violations related to the shot clock', 'https://official.nba.com/rule-no-7-24-second-clock/', 'article'),
('Equipment', 'Basketball Equipment Regulations', 'Official rules regarding player equipment and accessories', 'https://official.nba.com/rule-no-2-duties-of-the-officials/', 'article');